### ISSUE TITLE
Can't close Prompt Window

### ISSUE THREAD

**Issue by rTreutlein** [deifyed/naVi#8]
So i was playing around a bit and the prompt window stays open even if you switch to a different window. And then there is no way to close it.

**Comment by deifyed** [comment]
Hmm. I'm not able to reproduce. ESC should close the window, and if you somehow are able to enter normal mode you should be able to close it with `:bd` and/or `:wd`.

Any tips on how I can reproduce?

**Comment by deifyed** [comment]
Closed due to inactivity
