### ISSUE TITLE
No Results

### ISSUE THREAD

**Issue by rTreutlein** [deifyed/naVi#9]
So i tried the plugin but i don't get any response from ChatGPT. I have my open ai key set in the env. At least an error message of what went wrong would be nice.

**Comment by rTreutlein** [comment]
Okay i found the issue. I did set the API key wrong. I suggest you also look for OPENAI_API_KEY as that is used by various other apps. And if it's not found through an erro.

**Comment by deifyed** [comment]
Good suggestion!

**Comment by deifyed** [comment]
Fixed in 71339b5
